{% set name = "gcovr" %}
{% set version = "8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gcovr-{{ version }}.tar.gz
  sha256: faa371f9c4a7f78c9800da655107d4f99f04b718d1c0d9f48cafdcbef0049079

build:
  noarch: python
  entry_points:
    - gcovr = gcovr.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    # upstream sets this hard dependencies, version not available in conda forge
    - hatchling #==1.26.1
    - hatch-vcs ==0.4.0
    - hatch-fancy-pypi-readme ==24.1.0
    - pip
  run:
    - python >=3.9
    - jinja2
    - lxml
    - colorlog
    - pygments >=2.13.0
    - tomli >=1.1.0  # [py<311]

test:
  imports:
    - gcovr
  commands:
    - pip check
    - gcovr --help
  requires:
    - pip

about:
  home: http://gcovr.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: generate GCC code coverage reports
  description: |
    Gcovr provides a utility for managing the use of the GNU gcov utility and
    generating summarized code coverage results. This command is inspired by the
    Python coverage.py package, which provides a similar utility for Python.
  doc_url: http://gcovr.com/guide.html
  dev_url: https://github.com/gcovr/gcovr

extra:
  recipe-maintainers:
    - t-b
    - jdmarques
    - tovrstra
    - mjscosta
