{% set name = "gcovr" %}
{% set version = "8.3" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ name }}/{{ name }}.git
  git_rev: {{ version }}
  content_sha256: "288428ff58bf2356fd7f7fe386151d8166f27e6141610dbe038d3b79e66c6ae6"
  content_hash_skip:
    - .git

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - gcovr = gcovr.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
  run:
    - python >={{ python_min }}
    - pygments >=2.13.0
    - jinja2
    - lxml
    # require tomli for all python versions to keep it noarch
    # can be removed once 3.11 is the minimum version
    - tomli >=1.1.0
    - colorlog

test:
  requires:
    - python {{ python_min }}
  imports:
    - gcovr

about:
  home: http://gcovr.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: generate GCC code coverage reports
  description: |
    Gcovr provides a utility for managing the use of the GNU gcov utility and
    generating summarized code coverage results. This command is inspired by the
    Python coverage.py package, which provides a similar utility for Python.
  doc_url: http://gcovr.com/guide.html
  dev_url: https://github.com/gcovr/gcovr

extra:
  recipe-maintainers:
    - t-b
    - jdmarques
    - tovrstra
    - mjscosta
